# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/shoshan/installs/clion-2017.1.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/shoshan/installs/clion-2017.1.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shoshan/CLionProjects/learning-cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shoshan/CLionProjects/learning-cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/shoshan/installs/clion-2017.1.3/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/shoshan/installs/clion-2017.1.3/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/shoshan/installs/clion-2017.1.3/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/shoshan/installs/clion-2017.1.3/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/shoshan/installs/clion-2017.1.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/shoshan/installs/clion-2017.1.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shoshan/CLionProjects/learning-cmake/CMakeFiles /home/shoshan/CLionProjects/learning-cmake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shoshan/CLionProjects/learning-cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello-world-exe

# Build rule for target.
hello-world-exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello-world-exe
.PHONY : hello-world-exe

# fast build rule for target.
hello-world-exe/fast:
	$(MAKE) -f hello-world/CMakeFiles/hello-world-exe.dir/build.make hello-world/CMakeFiles/hello-world-exe.dir/build
.PHONY : hello-world-exe/fast

#=============================================================================
# Target rules for targets named hello-clear

# Build rule for target.
hello-clear: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello-clear
.PHONY : hello-clear

# fast build rule for target.
hello-clear/fast:
	$(MAKE) -f hello-world-clear/src/CMakeFiles/hello-clear.dir/build.make hello-world-clear/src/CMakeFiles/hello-clear.dir/build
.PHONY : hello-clear/fast

#=============================================================================
# Target rules for targets named hello_static

# Build rule for target.
hello_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_static
.PHONY : hello_static

# fast build rule for target.
hello_static/fast:
	$(MAKE) -f hello-world-lib/src/CMakeFiles/hello_static.dir/build.make hello-world-lib/src/CMakeFiles/hello_static.dir/build
.PHONY : hello_static/fast

#=============================================================================
# Target rules for targets named hello_dynamic

# Build rule for target.
hello_dynamic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_dynamic
.PHONY : hello_dynamic

# fast build rule for target.
hello_dynamic/fast:
	$(MAKE) -f hello-world-lib/src/CMakeFiles/hello_dynamic.dir/build.make hello-world-lib/src/CMakeFiles/hello_dynamic.dir/build
.PHONY : hello_dynamic/fast

#=============================================================================
# Target rules for targets named hello-world-lib

# Build rule for target.
hello-world-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello-world-lib
.PHONY : hello-world-lib

# fast build rule for target.
hello-world-lib/fast:
	$(MAKE) -f hello-world-shared/src/CMakeFiles/hello-world-lib.dir/build.make hello-world-shared/src/CMakeFiles/hello-world-lib.dir/build
.PHONY : hello-world-lib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hello-world-exe"
	@echo "... hello-clear"
	@echo "... hello_static"
	@echo "... hello_dynamic"
	@echo "... hello-world-lib"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

